[build]
  functions = "netlify/functions"
  publish = "dist"

[[redirects]]
  from = "/salvar"
  to = "/.netlify/functions/salvar"
  status = 200

[[redirects]]
  from = "/visualizar"
  to = "/.netlify/functions/visualizar"
  status = 200

[[redirects]]
  from = "/baixar"
  to = "/.netlify/functions/baixar"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
